- name: update aliases.
  remote_user: ulsprovision
  hosts: OS_group3
  become: yes

  tasks:
  
  
  - name: Replace ULS-Sysdev email with ULS-linux-root in /etc/aliases
    replace:
      path: /etc/aliases
      regexp: 'uls-systemsdevelopment@pitt.edu'
      replace: 'uls-linux-root@pitt.edu'
      backup: yes

  - name: add yumcron alias
    lineinfile:
      path: /etc/aliases
      line: "#yum-cron alias"
      insertafter: EOF
      backup: yes
      state: present

  - name: add yumcron email
    lineinfile:
      path: /etc/aliases
      line: "yumcron: mem375@pitt.edu,bdgregg@pitt.edu,ctgraham@pitt.edu"
      insertafter: EOF
      backup: yes
      state: present

  - name: Add yum-cron alias in /etc/sysconfig/yum-cron
    replace:
      path: /etc/sysconfig/yum-cron
      regexp: 'MAILTO='
      replace: 'MAILTO=yumcron'
      backup: yes
    when: (ansible_facts['distribution_major_version'] == "6")

  - name: Replace root  with yum-cron alias in /etc/yum/yum-cron.conf
    replace:
      path: /etc/yum/yum-cron.conf
      regexp: 'email_to = root'
      replace: 'email_to = yumcron'
      backup: yes
    when: (ansible_facts['distribution_major_version'] == "7")

  - name: Replace root  with yum-cron alias in /etc/dnf/automatic.conf
    replace:
      path: /etc/dnf/automatic.conf
      regexp: 'email_to = root'
      replace: 'email_to = yumcron'
      backup: yes
    when: (ansible_facts['distribution_major_version'] == "8")

  - name: restart yumcron
    service:
      name: yum-cron
      state: restarted
