
- name: oel 7.5 apache build
  remote_user: ulsprovision
  hosts: webservers
  become: yes

  tasks:
# every time we install/update httpd, reset file system permissions to trust users other than root to read apache logs
  - name: install yum-utils
    yum:
      name: yum-utils
      state: latest

  - name: install yum-plugin-post-transaction-actions
    yum:
      name: yum-plugin-post-transaction-actions
      state: latest

  - name: Trust users other than root to read apache logs
    copy:
      src: resources/httpd.action
      dest: "/etc/yum/post-actions/"


  - name: user can execute httpd.action
    file:
      path: /etc/yum/post-actions/httpd.action
      mode: "u+x"

  - name: install mod_ssl
    yum:
      name: mod_ssl
      state: latest

  - name: install certbot
    yum:
      name:
        - certbot
        - python2-certbot-apache
      state: latest

  - name: install clamav
    yum:
      name:
        - clamav
        - clamav-update
        - clamd
      state: latest

  - name: refresh clamav database
    command: "/usr/bin/freshclam --quiet"

  - name: enable freshclam as a cron
    cron:
      name: freshclam daily
      user: root
      job: "/usr/local/bin/cronic /usr/bin/freshclam --quiet"
      hour: 19
      minute: "{{ 59 | random }}"
      state: present

  - name: enable clamd socket
    lineinfile:
      path: /etc/clamd.d/scan.conf
      regexp: '^#LocalSocket (.*)$'
      line: 'LocalSocket \1'
      backrefs: yes

  - name: enable clamd service
    service:
      name: clamd@scan
      enabled: yes
      state: started

  - name: selinux allow daemons to talk to each other's sockets (httpd -> clamd@scan)
    seboolean:
      name: daemons_enable_cluster_mode
      state: yes
      persistent: yes

  - name: selinux allow apache to execute external programs (clamscan)
    seboolean:
      name: httpd_execmem
      state: yes
      persistent: yes

  - name: apache is a member of virusgroup
    user:
      name: apache
      groups: virusgroup

  - name: ensure httpd is running
    service:
      name: httpd
      enabled: yes
      state: started

#apache server
  - firewalld:
      service: http
      zone: public
      permanent: yes
      state: enabled

#apache server
  - firewalld:
      service: https
      zone: public
      permanent: yes
      state: enabled

  - name: reload firewalld
    service:
      name: firewalld
      state: reloaded

  - name: preserve 10 years of logs
    lineinfile:
      path: /etc/logrotate.d/httpd
      state: present
      insertafter: '^/var/log/httpd/\*log \{'
      line: '    rotate 520'
