
- name: oel 7.5 apache build
  remote_user: ulsprovision
  hosts: webservers
  become: yes

  tasks:
  #any apache
  - name: install mod_ssl
    yum:
      name: mod_ssl
      state: latest

  - name: install clamav
    yum:
      name:
        - clamav
        - clamav-update
        - clamd
      state: latest

  - name: ensure httpd is running
    service:
      name: httpd
      enabled: yes

#apache server
  - firewalld:
      service: http
      zone: public
      permanent: yes
      state: enabled

#apache server
  - firewalld:
      service: https
      zone: public
      permanent: yes
      state: enabled

  - name: reload firewalld
    service:
      name: firewalld
      state: reloaded

# every time we reload httpd, reset file system permissions to trust users other than root to read apache logs
#any apache server
  - name: install yum-utils
    yum:
      name: yum-utils
      state: latest

  - name: install yum-plugin-post-transaction-actions
    yum:
      name: yum-plugin-post-transaction-actions
      state: latest

  - name: Trust users other than root to read apache logs
    copy:
      src: resources/httpd.action
      dest: "/etc/yum/post-actions/"


  - name: user can execute httpd.action
    file:
      path: /etc/yum/post-actions/httpd.action
      mode: "u+x"
