
- name: oel 7.5 base build
  remote_user: ulsprovision
  hosts: all
  become: yes

  tasks:

  - name: install wget
    yum:
      name: wget
      state: latest

#candidate for addition to the base vmware template
  - name: add students group
    group:
      name: ulssysstu
      state: present


  - name: install rsync
    yum:
      name: rsync
      state: latest


  - name: install git
    yum:
      name: git
      state: latest

# add cronic

  - name: Add cronic script
    copy:
      src: resources/all/cronic
      dest: /usr/local/bin/cronic
      mode: u=rwx,g=rx,o=rx
      owner: root
      group: root


# selinux

  - name: install policycoreutils-python
    yum:
      name: policycoreutils-python
      state: latest


  - name: install libselinux-python
    yum:
      name: libselinux-python
      state: latest

  - name: set up email for root
    lineinfile:
       path: /etc/aliases
       state: present
       regexp: '^root:'
       line: 'root:           uls-linux-root@pitt.edu'

  - name: Install yum-cron.
    yum:
      name: yum-cron
      state: latest

  - name: Copy yum-cron.conf to host.
    template:
      src: resources/updates/yum-cron/yum-cron.conf
      dest: /etc/yum/yum-cron.conf

  - name: add yumcron email
    lineinfile:
      path: /etc/aliases
      line: "yumcron: mem375@pitt.edu,bdgregg@pitt.edu,ctgraham@pitt.edu"
      insertafter: EOF
      backup: yes
      state: present

  - name: Replace root  with yum-cron alias in /etc/yum/yum-cron.conf
    replace:
      path: /etc/yum/yum-cron.conf
      regexp: 'email_to = root'
      replace: 'email_to = yumcron'
      backup: yes

  - name: restart yumcron
    service:
      name: yum-cron
      state: restarted       
