- name: oel 7.5 php build
  remote_user: ulsprovision
  hosts: phpdevel
  become: yes

  tasks:

  - name: install php and extensions
    yum:
      name:
        - php73-php-devel
        - php73-php-pecl-xdebug
      state: present


  - name: enable development PHP errors
    lineinfile:
       create: yes
       path: /etc/php.d/zzz_local.ini
       state: present
       regexp: 'error_reporting.*'
       line: 'error_reporting=E_ALL'
