- name: oel 7.5 php build
  remote_user: ulsprovision
  hosts: phpclients
  become: yes

  tasks:

  - name: install php and extensions
    yum:
      name:
        - mod_php72w
        - php72w-gd
        - php72w-ldap
        - php72w-mbstring
        - php72w-mysql
        - php72w-pear
        - php72w-pdo
        - php72w-soap
        - php72w-intl
      state: present

#all builds with php
  - name: install mariadb
    yum:
      name:
        - mariadb
      state: present

  - name: set up PHP max execution time
    lineinfile:
       path: /etc/php.d/zzz_local.ini
       state: present
       regexp: 'max_execution_time.*'
       line: 'max_execution_time = 300'

  - name: set up PHP max post size
    lineinfile:
       path: /etc/php.d/zzz_local.ini
       state: present
       regexp: 'post_max_size.*'
       line: 'post_max_size = 256M'

  - name: set up PHP max upload size
    lineinfile:
       path: /etc/php.d/zzz_local.ini
       state: present
       regexp: 'upload_max_filesize.*'
       line: 'upload_max_filesize = 256M'

  - name: set up PHP timezone
    lineinfile:
       path: /etc/php.d/zzz_local.ini
       state: present
       regexp: 'date.timezone.*'
       line: 'date.timezone = America/New_York'
