- name: Set relayhost in postfix main.cf.
  remote_user: ulsprovision
  hosts: SE_Rocky8
  become: yes

  tasks:

  - name: Start and enable postfix service
    service:
      name: postfix
      state: started
      enabled: yes

  - name: add relayhost setting.
    lineinfile:
      path: /etc/postfix/main.cf
      line: relayhost = mail.scholarlyexchange.org
      insertafter: an.ip.add.ress
      backup: yes

  - name: reload postfix
    command: /usr/sbin/postfix reload
    
    
