- name: oel 7.5 text_processing build
  remote_user: ulsprovision
  hosts: textprocessors
  become: yes

  tasks:

  - name: install gcc
    yum:
      name:
        - gcc
      state: latest  

  - name: install automake
    yum:
      name:
        - automake
      state: latest  
  
  - name: install autoconf
    yum:
      name:
        - autoconf 
      state: latest  
         
   - name: install poppler-utils for pdftotext
    yum:
      name: poppler-utils
      state: latest

   - name: install catdoc
    yum:
      name: catdoc
      state: latest

#TODO: add local scripts catdox.sh and docx2txt.pl into /usr/local/bin/ 
