- name: UDA4 EZPAARSE install and config
  remote_user: ulsprovision
  hosts: uda4
  become: yes

  tasks:

    - name: Add ldap tooling
      yum:
        name: openldap-clients
        state: latest

    - name: Add rssh for remote scp/rsync
      yum:
        name: rssh
        state: latest

    - name: allow rsync
      lineinfile:
        path: /etc/rssh.conf
        state: present
        regexp: '^#?allowrsync$'
        line: 'allowrsync'

    - name: Import variables
      include_vars:
        file: "hostvars/{{inventory_hostname}}.ezpaarse-uda4.yml"
        name: ezpvars
     
    - name: Create a service user
      user:
        name: 'ezpdata'
        shell: /bin/rssh
        state: present
        group: 'ezpdata'
        groups: 'rsshusers'

    - name: set up email for ezpdata
      lineinfile:
        path: /etc/aliases
        state: present
        insertafter: '^support:'
        line: 'ezpdata:           root'

    - name: Create a data directory
      file:
        path: "{{ezpvars.EZPFILESDIR}}"
        state: directory
        group: ulssysdev
        owner: 'ezpdata'
        mode: '2770'
 
    - name: Create data subdirectories
      file:
        path: "{{ezpvars.EZPFILESDIR}}/{{item}}"
        state: directory
        group: ulssysdev
        owner: 'ezpdata'
        mode: '2770'
      with_items: 
        - pending
        - working
        - done
                    
    - name: Create an application directory
      file:
        path: /usr/local/ezpaarse-loader
        state: directory
        group: ulssysdev
        owner: root
        mode: '2775'

    - name: Clone from git
      git:
        repo: https://github.com/ulsdevteam/ezpaarse-loader.git
        dest: /usr/local/ezpaarse-loader
        force: yes

    - name: Set environment variables
      lineinfile:
        dest: /usr/local/ezpaarse-loader/common.env
        state: present
        create: yes
        line: 'export {{ item.key }}={{ item.value }}'
      with_items: '{{ ezpvars | dict2items }}'

    - name: Grant write access
      file:
        path: /usr/local/ezpaarse-loader
        recurse: yes
        mode: 'g+w'

    - name: Schedule cron process
      cron:
        name: 'Process EZPAARSE logs'
        hour: '5'
        minute: '37'
        job: '/usr/local/bin/cronic /usr/local/ezpaarse-loader/process.sh'
      become: yes
      become_user: 'ezpdata'

    - name: Schedule cron postprocess
      cron:
        name: 'Postprocess EZPAARSE data load'
        hour: '15'
        minute: '37'
        job: '/usr/local/bin/cronic /usr/local/ezpaarse-loader/postprocess.sh'
      become: yes
      become_user: 'ezpdata'

    - name: Schedule cron for sponsored accounts
      cron:
        name: 'Calculate RCs for Sponsored Accounts'
        day: '6'
        hour: '4'
        minute: '37'
        job: '/usr/local/bin/cronic /usr/local/ezpaarse-loader/sponsor.sh'
      become: yes
      become_user: 'ezpdata'

    - name: set up email for root
      lineinfile:
         path: /etc/aliases
         state: present
         regexp: '^ezpdata:'
         line: 'ezpdata:           root'
