http: "http_proxy=http://proxy.it.pitt.edu:8080"
ftp: "ftp_proxy=http://proxy.it.pitt.edu:8080"
https: "https_proxy=http://proxy.it.pitt.edu:8080"
no_proxy: "no_proxy='127.0.0.1,localhost,*.pitt.edu'"
