- name: RHEL Software Collections
  remote_user: ulsprovision
  hosts: rhscl
  become: yes

  tasks:
 
  - name: Enable a Red Hat Software Collections
    community.general.rhsm_repository:
      name: rhel-server-rhscl-7-rpms

  - name: Enable a Red Hat Server Optional
    community.general.rhsm_repository:
      name: rhel-7-server-optional-rpms

