- name: Python Build 3.6
  remote_user: ulsprovision
  hosts: rhscl_py36
  become: yes

  tasks:

  - name: install python and extensions
    yum:
      name:
        - rh-python36
      state: present

  - name: Enable python for all users
    copy:
      dest: "/etc/profile.d/enablepython.sh"
      content: |
        #!/bin/bash
        source scl_source enable rh-python36
